// <auto-generated />
using System;
using CMP1005_AMSApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMP1005_AMSApiService.Migrations
{
    [DbContext(typeof(AMSDBContext))]
    [Migration("20221214032604_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AMSLibrary.Models.Gathering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttendeesCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GatheringDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatheringLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gatherings");
                });
#pragma warning restore 612, 618
        }
    }
}
